### ISSUE TITLE
Test Failed (DLL load failed)

### ISSUE THREAD

**Issue by lazzero** [WISDEM/CCBlade#18]
Hi, I am trying to launch CCBlade test (test_ccblade.py) but I get the following error:

```
Traceback (most recent call last):
   File "test/test_ccblade.py", line 20, in <module>
     from ccblade import CCAirfoil, CCBlade
   File "C:\Python36\lib\site-packages\ccblade-1.1.1-py3.6-winmd64.egg\ccblade\__init__.py", line 1, in <module>
     from .ccblade import CCAirfoil, CCBlade
   File "C:\Python36\lib\site-packages\ccblade-1.1.1-py3.6-win-amd64.egg\ccblade\ccblade.py", line 31, in <module>
     import _bem
 ImportError: DLL load failed: Can't find the specified module.
```

I built CCBlade under Cygwin, I can't find any error message when building the code. Anyone can understand why after an apparently good installation the module is missing?

**Comment by evan-gaertner** [comment]
Its been quite some time since I installed Wisdem using Cygwin.  We've improved many of the installation and compiling issues in Windows, mading Wisdem available through Anaconda.  I would suggest following the installation instructions for developers here: https://github.com/WISDEM/WISDEM/tree/master where the compilers needed get added to your conda environment.

If you're still having issues, please share the debug information output to screen during the installation/compiling.
