### ISSUE TITLE
Trouble running CCBlade

### ISSUE THREAD

**Issue by matsupe** [WISDEM/CCBlade#2]
The unit test for the gradients fails, see A).
The tutorial works up to the point where dNp and dTp are calculated, see B).

A)

Matias@MATIAS-PC C:\CCBlade-master
$ python test\test_gradients.py
...F...................................................................
======================================================================
FAIL: test_dRhub1 (__main__.TestGradients)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test\test_gradients.py", line 379, in test_dRhub1
    np.testing.assert_allclose(dNp_dRhub_fd, dNp_dRhub, rtol=1e-5, atol=1e-7)
  File "C:\WinPython_32bit_27_10_1\python-2.7.10\lib\site-packages\numpy\testing\utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "C:\WinPython_32bit_27_10_1\python-2.7.10\lib\site-packages\numpy\testing\utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-05, atol=1e-07

(mismatch 100.0%)
 x: array([[ -5.791395e+00],
       [ -2.695933e-01],
       [ -2.843194e-03],...
 y: array([[ -5.791389e+000],
       [ -2.695926e-001],
       [ -2.843172e-003],...

----------------------------------------------------------------------
Ran 71 tests in 25.005s

FAILED (failures=1)

Matias@MATIAS-PC C:\CCBlade-master
$

B)

Matias@MATIAS-PC C:\CCBlade-master\test\5MW_AFFiles
$ python Tutorial.py
CP = [ 0.46488091]
CT = [ 0.76926392]
CQ = [ 0.06163229]
Traceback (most recent call last):
  File "Tutorial.py", line 208, in <module>
    = rotor.distributedAeroLoads(Uinf, Omega, pitch, azimuth)
  File "C:\WinPython_32bit_27_10_1\python-2.7.10\lib\site-packages\ccblade-1.1.1-py2.7-win32.egg\ccblade.py", line 529, in distributedAeroLoads
    self.pitch = radians(pitch)
TypeError: only length-1 arrays can be converted to Python scalars

Matias@MATIAS-PC C:\CCBlade-master\test\5MW_AFFiles
$

**Comment by andrewning** [comment]
I checked and there isn't anything wrong with the gradients.  You can see that they are really close.  Comparing to finite differencing is always an rough check, and it looks like some of the tolerances I initially chose are too tight.  Perhaps a change in numpy version caused some small numerical differences.  I can adjust the tolerances.

I'm not sure what the problem is you are seeing with the tutorial.  I copy/pasted the tutorial and it ran fine for me.  It looks like you might be passing in an array for pitch instead of a scalar?
