### ISSUE TITLE
Errors importing Aerodyn files

### ISSUE THREAD

**Issue by sunnyxxchen** [WISDEM/CCBlade#21]
I am trying to use CCBlade to create CP/CT tables for the CART3 turbine using CART3 airfoil data. However, I get some errors when trying to import the Aerodyn files. One error appears to occur during the spline fitting process:

`Traceback (most recent call last):
  File "/home/schen/code/research/wind_farms/farm_fatigue/cp_ct/gen_table.py", line 34, in <module>
    airfoil_types[0] = afinit(directory + "AeroData/C3_01-02_Circle.dat")
  File "/usr/lib/python3.10/site-packages/CCBlade-1.2.0-py3.10-linux-x86_64.egg/ccblade/ccblade.py", line 110, in initFromAerodynFile
    return cls(alpha, Re, cl, cd, cm=cm)
  File "/usr/lib/python3.10/site-packages/CCBlade-1.2.0-py3.10-linux-x86_64.egg/ccblade/ccblade.py", line 88, in __init__
    self.cl_spline = RectBivariateSpline(alpha, Re, cl, kx=kx, ky=ky, s=0.1)
  File "/usr/lib/python3.10/site-packages/scipy/interpolate/_fitpack2.py", line 1345, in __init__
    nx, tx, ny, ty, c, fp, ier = dfitpack.regrid_smth(x, y, z, xb, xe, yb,
dfitpack.error: (1<=kx && kx<=5) failed for 5th keyword kx: regrid_smth:kx=0
`

while I'm not sure what's causing the other one (some sort of formatting issue?)

`Traceback (most recent call last):
  File "/home/schen/code/research/wind_farms/farm_fatigue/cp_ct/gen_table.py", line 34, in <module>
    airfoil_types[6] = afinit(directory + "AeroData/C3_08_4S818+3S816.dat")
  File "/usr/lib/python3.10/site-packages/CCBlade-1.2.0-py3.10-linux-x86_64.egg/ccblade/ccblade.py", line 108, in initFromAerodynFile
    af = Airfoil.initFromAerodynFile(aerodynFile)
  File "/usr/lib/python3.10/site-packages/CCBlade-1.2.0-py3.10-linux-x86_64.egg/ccblade/airfoilprep.py", line 589, in initFromAerodynFile
    cm.append(data[3])
IndexError: list index out of range
`

The Aerodyn files are supposed to compatible with Aerodyn V13.0.

Thanks in advance for your help!

**Comment by gbarter** [comment]
Would you be able to post the input file you are using so that we more easily test out and debug the issue?

**Comment by sunnyxxchen** [comment]
This file produces the spline fitting error.
[C3_01-02_Circle.dat.txt](https://github.com/WISDEM/CCBlade/files/8113564/C3_01-02_Circle.dat.txt)

This file causes the IndexError.
[C3_03_2Cir+1S818.dat.txt](https://github.com/WISDEM/CCBlade/files/8113563/C3_03_2Cir%2B1S818.dat.txt)

(I appended .txt so that I could upload these files to Github, but you can remove them.)

**Comment by gbarter** [comment]
Thanks, there is a common error in both files and an additional error in the `C3_O3_2Cir+1S818.dat` file.  This was difficult to see because the errors were so abstruse.  I have tried to add some additional checks and warnings among the changes in #22.  If you update your local checkout with these changes, you will have to rebuild and reinstall, even if you did `pip install -e` or `python setup.py develop` as there are changes to the underlying Fortran source.

In both files, you were missing the _Control Setting_ parameter line in each polar, which you can see [here](https://github.com/WISDEM/CCBlade/blob/master/test/5MW_AFFiles/Cylinder1.dat#L6).  In the second file (`C3_O3_2Cir+1S818.dat`), your airfoil polar data is missing the moment coefficient column.  The entries on each polar line are:
```alpha cl cd cm```

Here is the updated version of your first file that runs fine.
[C3_01-02_Circle-revised.dat.txt](https://github.com/WISDEM/CCBlade/files/8117801/C3_01-02_Circle-revised.dat.txt)

**Comment by sunnyxxchen** [comment]
Thanks for getting back to me. The missing data does seem to be causing my error. Is there an option to import the data without providing the moment coefficient information? In the Aerodyn .ipt file, I can specify whether or not to use a pitching moment model (re: [AeroDyn V13 manual, pg. 7](https://www.nrel.gov/wind/nwtc/assets/text/aerodyn.pdf)). I do not believe that I would need this information for my application.

**Comment by gbarter** [comment]
You can just use zero for the moment coefficient with CCBlade and things should work.

**Comment by sunnyxxchen** [comment]
Thank you for your help!
